services:
  private-gpt:
    build:
      dockerfile: Dockerfile.external
    user: root
    volumes:
      - ./local_data/:/home/worker/app/local_data
    ports:
      - 8001:8080
    environment:
      PORT: 8080
      PGPT_PROFILES: docker
      PGPT_MODE: ollama
  ollama:
    build:
      dockerfile: Dockerfile.ollama
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 0
            capabilities: [gpu]
    user: root
    volumes:
      - ./models:/root/.ollama
